fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    chocolatey: 'https://github.com/puppetlabs/puppetlabs-chocolatey.git'
    registry: 'https://github.com/puppetlabs/puppetlabs-registry.git'
    powershell: 'https://github.com/puppetlabs/puppetlabs-powershell.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
