---
Gemfile:
  optional:
    ':test':
      - gem: 'toml-rb'
    ':system_tests':
      - gem: 'toml-rb'
spec/spec_helper.rb:
  hiera_config: "'spec/hiera.yaml'"
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
